### ISSUE TITLE
Add configurable cooldown between teleports / required time standing still before teleports

### ISSUE THREAD

**Issue by Gandalf360one** [percyqaz/LodestoneTeleport#2]
Could you pls update it to minecraft 1.18?

I have also some suggestion (if possible)
- The Teleportation has a cooldown
- When you use the compass you have to stand still for some secs before you get teleportet
- You wont get teleportet when you move in that time

**Comment by percyqaz** [comment]
Hi! I'm updating my Minecraft server to 1.18 at the start of the new year (Jan 1st), so at the very latest the plugin will be updated by then (though if I get some time I could update it this weekend)

Thanks for the suggestion, I agree with it but I am not a very experienced plugin developer so I'd have to learn a lot in order to add those things

The main bug I'm worried about is when you right click with a compass and then drop it/put it away, but after a few secs of standing still you still teleport for free

For the time being I'll keep the plugin simple so I know there can't be any bugs in it, but I will investigate a bit into adding that suggestion :)

**Comment by percyqaz** [comment]
Update: I've just updated it to 1.18.1 (should work on 1.18 also if you're using that) - See releases [here](https://github.com/percyqaz/LodestoneTeleport/releases)

When I get a bit more time I'll have a look into cooldowns/charge up times for teleporting

**Comment by Gandalf360one** [comment]
Nice!

**Comment by percyqaz** [comment]
Hi, I've just released a new version that has configurable cooldowns/required standing still time

Enjoy :)
